name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to describe the issue
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please briefly describe the issue encountered
      placeholder: Tell us what you saw.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what should have happened.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Tell us what actually happened.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please briefly outline the steps taken prior to encountering the issue
      placeholder: |
        1. Go here
        2. Do this
        3. ...
    validations:
      required: false
